
admin username: LL4wliet
api token: 917583816:AAG-Jf82LgKFrEFS_ECgbjF7VYVpGwOOjdo
db engine: sqlite:///fairybang.db?check_same_thread=False

enable tor: True

# Debug: True (polling) / False (webhooks)
debug: True

qiwi:
  - +7 921 777 77 77
  - +7 922 888 88 88

countries:
  - ğŸ‡·ğŸ‡º Ğ Ğ¾ÑÑĞ¸Ñ

promocodes:
  - 5%: FB12NMQ4
  - 10%: FB89LKJ2